apiVersion: apps/v1
kind: Deployment
metadata:
  name: manageweb
  namespace: kube-<NAMESPACES>
spec:
  selector:
    matchLabels:
      app: manageweb
  replicas: 1
  template:
    metadata:
      labels:
        app: manageweb
    spec:
      containers:
        - image: 10.6.1.45:10242/cyg/manageweb:<BUILD_TAG>
          imagePullPolicy: IfNotPresent
          name: manageweb
          env:
            - name: branch
              value: <BRANCH_NAME>
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: '/etc/localtime'
              name: timezone
          resources:
            requests:
              cpu: '500m'
              memory: '500Mi'
              ephemeral-storage: 700Mi
            limits:
              cpu: '0.8'
              memory: '0.8Gi'
              ephemeral-storage: 0.8Gi
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: manageweb
  name: manageweb
  namespace: kube-<NAMESPACES>
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
  selector:
    app: manageweb
