apiVersion: apps/v1
kind: Deployment
metadata:
  name: manageweb
  namespace: kube-<NAMESPACES>
spec:
  selector:
    matchLabels:
      app: manageweb
  replicas: 1
  template:
    metadata:
      labels:
        app: manageweb
    spec:
      containers:
        - image: 10.6.1.45:10242/cyg/manageweb:<BUILD_TAG>
          imagePullPolicy: IfNotPresent
          name: manageweb
          env:
            - name: branch
              value: <BRANCH_NAME>
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: '100m'
              memory: '100Mi'
              ephemeral-storage: 100Mi
            limits:
              cpu: '0.2'
              memory: '0.2Gi'
              ephemeral-storage: 0.2Gi

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: manageweb
  name: manageweb
  namespace: kube-<NAMESPACES>
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
  selector:
    app: manageweb
